name: urban_hamony
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^3.5.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_database: ^11.1.3
  shared_preferences: ^2.3.2
  image_cropper: ^5.0.0
  image_picker: ^0.8.4+4
  dotted_border: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  firebase_storage: ^12.3.1
  path: ^1.9.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  android: true
  ios: false
  web: true


  background_image: "lib/assets/images/background_splash.jpg"
  image: "lib/assets/images/logo_mini.png"
  android_12:
    color: "#FFFFFF"
    background_image: "lib/assets/images/background_splash.jpg"
    image: "lib/assets/images/logo_mini.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/images/


  uses-material-design: true


